/**
 * Acciones de auditoría para el sistema de trazabilidad
 * Todas las operaciones importantes deben ser registradas
 */
export enum AuditAction {
  // Autenticación y autorización
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  
  // Gestión de usuarios
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_ROLE_ASSIGNED = 'USER_ROLE_ASSIGNED',
  USER_ROLE_REMOVED = 'USER_ROLE_REMOVED',
  USER_PROFILE_VIEWED = 'USER_PROFILE_VIEWED',
  
  // Gestión de tenants/organizaciones
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_DELETED = 'TENANT_DELETED',
  TENANT_ACTIVATED = 'TENANT_ACTIVATED',
  TENANT_DEACTIVATED = 'TENANT_DEACTIVATED',
  TENANT_PLAN_CHANGED = 'TENANT_PLAN_CHANGED',
  TENANT_SETTINGS_CHANGED = 'TENANT_SETTINGS_CHANGED',
  
  // Gestión documental
  DOCUMENT_CREATED = 'DOCUMENT_CREATED',
  DOCUMENT_UPDATED = 'DOCUMENT_UPDATED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  DOCUMENT_VIEWED = 'DOCUMENT_VIEWED',
  DOCUMENT_DOWNLOADED = 'DOCUMENT_DOWNLOADED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_VERSION_CREATED = 'DOCUMENT_VERSION_CREATED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  DOCUMENT_PUBLISHED = 'DOCUMENT_PUBLISHED',
  DOCUMENT_OBSOLETED = 'DOCUMENT_OBSOLETED',
  DOCUMENT_RESTORED = 'DOCUMENT_RESTORED',
  DOCUMENT_SHARED = 'DOCUMENT_SHARED',
  DOCUMENT_SIGNED = 'DOCUMENT_SIGNED',
  
  // Gestión de procesos
  PROCESS_CREATED = 'PROCESS_CREATED',
  PROCESS_UPDATED = 'PROCESS_UPDATED',
  PROCESS_DELETED = 'PROCESS_DELETED',
  PROCESS_VIEWED = 'PROCESS_VIEWED',
  PROCESS_ACTIVATED = 'PROCESS_ACTIVATED',
  PROCESS_DEACTIVATED = 'PROCESS_DEACTIVATED',
  PROCESS_OWNER_ASSIGNED = 'PROCESS_OWNER_ASSIGNED',
  PROCESS_RISK_ASSESSED = 'PROCESS_RISK_ASSESSED',
  PROCESS_KPI_UPDATED = 'PROCESS_KPI_UPDATED',
  
  // Auditorías
  AUDIT_CREATED = 'AUDIT_CREATED',
  AUDIT_UPDATED = 'AUDIT_UPDATED',
  AUDIT_DELETED = 'AUDIT_DELETED',
  AUDIT_PLANNED = 'AUDIT_PLANNED',
  AUDIT_STARTED = 'AUDIT_STARTED',
  AUDIT_COMPLETED = 'AUDIT_COMPLETED',
  AUDIT_CANCELLED = 'AUDIT_CANCELLED',
  AUDIT_REPORT_GENERATED = 'AUDIT_REPORT_GENERATED',
  AUDIT_FINDING_CREATED = 'AUDIT_FINDING_CREATED',
  AUDIT_EVIDENCE_UPLOADED = 'AUDIT_EVIDENCE_UPLOADED',
  
  // No conformidades y CAPA
  NC_CREATED = 'NC_CREATED',
  NC_UPDATED = 'NC_UPDATED',
  NC_DELETED = 'NC_DELETED',
  NC_ASSIGNED = 'NC_ASSIGNED',
  NC_STATUS_CHANGED = 'NC_STATUS_CHANGED',
  NC_CLOSED = 'NC_CLOSED',
  NC_REOPENED = 'NC_REOPENED',
  CAPA_CREATED = 'CAPA_CREATED',
  CAPA_UPDATED = 'CAPA_UPDATED',
  CAPA_IMPLEMENTED = 'CAPA_IMPLEMENTED',
  CAPA_VERIFIED = 'CAPA_VERIFIED',
  ROOT_CAUSE_ANALYSIS = 'ROOT_CAUSE_ANALYSIS',
  
  // Capacitaciones
  TRAINING_CREATED = 'TRAINING_CREATED',
  TRAINING_UPDATED = 'TRAINING_UPDATED',
  TRAINING_DELETED = 'TRAINING_DELETED',
  TRAINING_SCHEDULED = 'TRAINING_SCHEDULED',
  TRAINING_COMPLETED = 'TRAINING_COMPLETED',
  TRAINING_CANCELLED = 'TRAINING_CANCELLED',
  TRAINING_ATTENDED = 'TRAINING_ATTENDED',
  TRAINING_EVALUATED = 'TRAINING_EVALUATED',
  COMPETENCE_ASSESSED = 'COMPETENCE_ASSESSED',
  COMPETENCE_UPDATED = 'COMPETENCE_UPDATED',
  
  // Indicadores y métricas
  INDICATOR_CREATED = 'INDICATOR_CREATED',
  INDICATOR_UPDATED = 'INDICATOR_UPDATED',
  INDICATOR_DELETED = 'INDICATOR_DELETED',
  INDICATOR_DATA_COLLECTED = 'INDICATOR_DATA_COLLECTED',
  INDICATOR_TARGET_SET = 'INDICATOR_TARGET_SET',
  INDICATOR_ALERT_TRIGGERED = 'INDICATOR_ALERT_TRIGGERED',
  METRIC_CALCULATED = 'METRIC_CALCULATED',
  KPI_DASHBOARD_VIEWED = 'KPI_DASHBOARD_VIEWED',
  
  // Reportes
  REPORT_GENERATED = 'REPORT_GENERATED',
  REPORT_EXPORTED = 'REPORT_EXPORTED',
  REPORT_SHARED = 'REPORT_SHARED',
  REPORT_SCHEDULED = 'REPORT_SCHEDULED',
  DASHBOARD_VIEWED = 'DASHBOARD_VIEWED',
  ANALYTICS_ACCESSED = 'ANALYTICS_ACCESSED',
  
  // Notificaciones
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  NOTIFICATION_READ = 'NOTIFICATION_READ',
  NOTIFICATION_DELETED = 'NOTIFICATION_DELETED',
  REMINDER_CREATED = 'REMINDER_CREATED',
  ALERT_TRIGGERED = 'ALERT_TRIGGERED',
  EMAIL_SENT = 'EMAIL_SENT',
  SMS_SENT = 'SMS_SENT',
  
  // Búsqueda y navegación
  SEARCH_PERFORMED = 'SEARCH_PERFORMED',
  ADVANCED_SEARCH = 'ADVANCED_SEARCH',
  FILTER_APPLIED = 'FILTER_APPLIED',
  EXPORT_REQUESTED = 'EXPORT_REQUESTED',
  BULK_OPERATION = 'BULK_OPERATION',
  
  // Configuración del sistema
  SYSTEM_CONFIG_CHANGED = 'SYSTEM_CONFIG_CHANGED',
  BACKUP_CREATED = 'BACKUP_CREATED',
  BACKUP_RESTORED = 'BACKUP_RESTORED',
  DATABASE_MIGRATED = 'DATABASE_MIGRATED',
  INTEGRATION_CONFIGURED = 'INTEGRATION_CONFIGURED',
  WEBHOOK_TRIGGERED = 'WEBHOOK_TRIGGERED',
  
  // Seguridad
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  
  // Integraciones
  ERP_SYNC = 'ERP_SYNC',
  CRM_SYNC = 'CRM_SYNC',
  SSO_LOGIN = 'SSO_LOGIN',
  API_CALL = 'API_CALL',
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  
  // Archivos y almacenamiento
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DOWNLOADED = 'FILE_DOWNLOADED',
  FILE_DELETED = 'FILE_DELETED',
  FILE_MOVED = 'FILE_MOVED',
  FILE_SHARED = 'FILE_SHARED',
  
  // Errores y excepciones
  ERROR_OCCURRED = 'ERROR_OCCURRED',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
}

/**
 * Niveles de criticidad para las acciones de auditoría
 */
export enum AuditLevel {
  LOW = 'LOW',           // Operaciones de lectura, navegación
  MEDIUM = 'MEDIUM',     // Operaciones de escritura normales
  HIGH = 'HIGH',         // Operaciones críticas del negocio
  CRITICAL = 'CRITICAL', // Operaciones de seguridad y configuración
}

/**
 * Mapeo de acciones a niveles de criticidad
 */
export const AUDIT_ACTION_LEVELS: Record<AuditAction, AuditLevel> = {
  // Nivel CRITICAL - Seguridad y configuración
  [AuditAction.LOGIN_FAILED]: AuditLevel.CRITICAL,
  [AuditAction.SECURITY_VIOLATION]: AuditLevel.CRITICAL,
  [AuditAction.SUSPICIOUS_ACTIVITY]: AuditLevel.CRITICAL,
  [AuditAction.SYSTEM_CONFIG_CHANGED]: AuditLevel.CRITICAL,
  [AuditAction.PERMISSION_GRANTED]: AuditLevel.CRITICAL,
  [AuditAction.PERMISSION_REVOKED]: AuditLevel.CRITICAL,
  [AuditAction.USER_ROLE_ASSIGNED]: AuditLevel.CRITICAL,
  [AuditAction.USER_ROLE_REMOVED]: AuditLevel.CRITICAL,
  [AuditAction.BACKUP_RESTORED]: AuditLevel.CRITICAL,
  [AuditAction.DATABASE_MIGRATED]: AuditLevel.CRITICAL,
  
  // Nivel HIGH - Operaciones críticas del negocio
  [AuditAction.USER_CREATED]: AuditLevel.HIGH,
  [AuditAction.USER_DELETED]: AuditLevel.HIGH,
  [AuditAction.TENANT_CREATED]: AuditLevel.HIGH,
  [AuditAction.TENANT_DELETED]: AuditLevel.HIGH,
  [AuditAction.DOCUMENT_APPROVED]: AuditLevel.HIGH,
  [AuditAction.DOCUMENT_PUBLISHED]: AuditLevel.HIGH,
  [AuditAction.DOCUMENT_OBSOLETED]: AuditLevel.HIGH,
  [AuditAction.AUDIT_COMPLETED]: AuditLevel.HIGH,
  [AuditAction.NC_CLOSED]: AuditLevel.HIGH,
  [AuditAction.CAPA_VERIFIED]: AuditLevel.HIGH,
  [AuditAction.BACKUP_CREATED]: AuditLevel.HIGH,
  
  // Nivel MEDIUM - Operaciones de escritura normales
  [AuditAction.LOGIN]: AuditLevel.MEDIUM,
  [AuditAction.LOGOUT]: AuditLevel.MEDIUM,
  [AuditAction.USER_UPDATED]: AuditLevel.MEDIUM,
  [AuditAction.DOCUMENT_CREATED]: AuditLevel.MEDIUM,
  [AuditAction.DOCUMENT_UPDATED]: AuditLevel.MEDIUM,
  [AuditAction.DOCUMENT_UPLOADED]: AuditLevel.MEDIUM,
  [AuditAction.PROCESS_CREATED]: AuditLevel.MEDIUM,
  [AuditAction.PROCESS_UPDATED]: AuditLevel.MEDIUM,
  [AuditAction.AUDIT_CREATED]: AuditLevel.MEDIUM,
  [AuditAction.NC_CREATED]: AuditLevel.MEDIUM,
  [AuditAction.TRAINING_CREATED]: AuditLevel.MEDIUM,
  [AuditAction.INDICATOR_CREATED]: AuditLevel.MEDIUM,
  [AuditAction.NOTIFICATION_SENT]: AuditLevel.MEDIUM,
  
  // Nivel LOW - Operaciones de lectura y navegación
  [AuditAction.DOCUMENT_VIEWED]: AuditLevel.LOW,
  [AuditAction.DOCUMENT_DOWNLOADED]: AuditLevel.LOW,
  [AuditAction.PROCESS_VIEWED]: AuditLevel.LOW,
  [AuditAction.SEARCH_PERFORMED]: AuditLevel.LOW,
  [AuditAction.DASHBOARD_VIEWED]: AuditLevel.LOW,
  [AuditAction.REPORT_GENERATED]: AuditLevel.LOW,
  [AuditAction.NOTIFICATION_READ]: AuditLevel.LOW,
  [AuditAction.USER_PROFILE_VIEWED]: AuditLevel.LOW,
  [AuditAction.KPI_DASHBOARD_VIEWED]: AuditLevel.LOW,
  [AuditAction.ANALYTICS_ACCESSED]: AuditLevel.LOW,
} as any;

/**
 * Obtiene el nivel de criticidad de una acción de auditoría
 * @param action Acción de auditoría
 * @returns Nivel de criticidad
 */
export function getAuditLevel(action: AuditAction): AuditLevel {
  return AUDIT_ACTION_LEVELS[action] || AuditLevel.MEDIUM;
}

/**
 * Verifica si una acción requiere retención a largo plazo
 * @param action Acción de auditoría
 * @returns true si requiere retención a largo plazo
 */
export function requiresLongTermRetention(action: AuditAction): boolean {
  const level = getAuditLevel(action);
  return level === AuditLevel.CRITICAL || level === AuditLevel.HIGH;
}