// Constantes para el sistema de jerarquía de agentes
export const HIERARCHY_CONSTANTS = {
  // Niveles de jerarquía
  HIERARCHY_LEVELS: {
    SUPER_COORDINATOR: 1,
    AREA_COORDINATOR: 2,
    SPECIALIZED_AGENT: 3
  },

  // Tipos de jerarquía
  HIERARCHY_TYPES: {
    FUNCTIONAL: 'functional',
    GEOGRAPHICAL: 'geographical',
    TEMPORAL: 'temporal',
    SECURITY: 'security',
    PERFORMANCE: 'performance',
    HYBRID: 'hybrid'
  },

  // Estados de jerarquía
  HIERARCHY_STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    MAINTENANCE: 'maintenance',
    ERROR: 'error',
    SCALING: 'scaling',
    FAILOVER: 'failover'
  },

  // Roles en la jerarquía
  HIERARCHY_ROLES: {
    LEADER: 'leader',
    FOLLOWER: 'follower',
    COORDINATOR: 'coordinator',
    WORKER: 'worker',
    MONITOR: 'monitor',
    BACKUP: 'backup'
  },

  // Configuración por defecto
  DEFAULT_CONFIG: {
    MAX_LEVELS: 5,
    MAX_AGENTS_PER_LEVEL: 100,
    MAX_COORDINATORS_PER_AREA: 10,
    MAX_SPECIALIZED_AGENTS_PER_COORDINATOR: 50,
    HIERARCHY_DEPTH: 3,
    COORDINATION_INTERVAL: 30000, // 30 segundos
    HEALTH_CHECK_INTERVAL: 60000, // 1 minuto
    FAILOVER_TIMEOUT: 300000, // 5 minutos
    SCALING_THRESHOLD: 0.8, // 80%
    LOAD_BALANCING_ENABLED: true,
    AUTO_SCALING_ENABLED: true,
    FAILOVER_ENABLED: true,
    BACKUP_ENABLED: true,
    MONITORING_ENABLED: true,
    LOGGING_ENABLED: true,
    AUDITING_ENABLED: true,
    SECURITY_ENABLED: true,
    PERFORMANCE_OPTIMIZATION_ENABLED: true,
    RESOURCE_MANAGEMENT_ENABLED: true
  },

  // Límites del sistema
  SYSTEM_LIMITS: {
    MAX_HIERARCHIES: 100,
    MAX_LEVELS_PER_HIERARCHY: 10,
    MAX_AGENTS_PER_HIERARCHY: 1000,
    MAX_COORDINATORS_PER_HIERARCHY: 100,
    MAX_SPECIALIZED_AGENTS_PER_HIERARCHY: 900,
    MAX_COMMUNICATION_CHANNELS: 1000,
    MAX_PERMISSIONS_PER_AGENT: 100,
    MAX_ROLES_PER_AGENT: 10,
    MAX_POLICIES_PER_HIERARCHY: 100,
    MAX_RULES_PER_POLICY: 100,
    MAX_EXCEPTIONS_PER_RULE: 50,
    MAX_ESCALATIONS_PER_HIERARCHY: 20,
    MAX_BACKUPS_PER_HIERARCHY: 10,
    MAX_MONITORS_PER_HIERARCHY: 50,
    MAX_AUDITORS_PER_HIERARCHY: 20,
    MAX_SECURITY_AGENTS_PER_HIERARCHY: 30,
    MAX_PERFORMANCE_AGENTS_PER_HIERARCHY: 30,
    MAX_RESOURCE_AGENTS_PER_HIERARCHY: 30,
    MAX_COMMUNICATION_AGENTS_PER_HIERARCHY: 30,
    MAX_WORKFLOW_AGENTS_PER_HIERARCHY: 30,
    MAX_TASK_AGENTS_PER_HIERARCHY: 30,
    MAX_DATABASE_AGENTS_PER_HIERARCHY: 20,
    MAX_API_AGENTS_PER_HIERARCHY: 20,
    MAX_WEB_AGENTS_PER_HIERARCHY: 20,
    MAX_MIGRATION_AGENTS_PER_HIERARCHY: 10,
    MAX_BACKUP_AGENTS_PER_HIERARCHY: 10,
    MAX_RESTORE_AGENTS_PER_HIERARCHY: 10,
    MAX_MAINTENANCE_AGENTS_PER_HIERARCHY: 10,
    MAX_SCALING_AGENTS_PER_HIERARCHY: 10,
    MAX_FAILOVER_AGENTS_PER_HIERARCHY: 10,
    MAX_RECOVERY_AGENTS_PER_HIERARCHY: 10,
    MAX_OPTIMIZATION_AGENTS_PER_HIERARCHY: 10,
    MAX_CLEANUP_AGENTS_PER_HIERARCHY: 10,
    MAX_GARBAGE_COLLECTION_AGENTS_PER_HIERARCHY: 10,
    MAX_SYSTEM_AGENTS_PER_HIERARCHY: 10,
    MAX_CUSTOM_AGENTS_PER_HIERARCHY: 50
  },

  // Timeouts
  TIMEOUTS: {
    HIERARCHY_CREATION: 60000, // 1 minuto
    HIERARCHY_DELETION: 30000, // 30 segundos
    HIERARCHY_UPDATE: 30000, // 30 segundos
    AGENT_REGISTRATION: 10000, // 10 segundos
    AGENT_DEREGISTRATION: 10000, // 10 segundos
    ROLE_ASSIGNMENT: 5000, // 5 segundos
    PERMISSION_GRANT: 5000, // 5 segundos
    POLICY_APPLICATION: 15000, // 15 segundos
    RULE_EVALUATION: 5000, // 5 segundos
    ESCALATION_PROCESS: 30000, // 30 segundos
    BACKUP_CREATION: 300000, // 5 minutos
    BACKUP_RESTORATION: 600000, // 10 minutos
    FAILOVER_PROCESS: 120000, // 2 minutos
    SCALING_PROCESS: 180000, // 3 minutos
    RECOVERY_PROCESS: 300000, // 5 minutos
    OPTIMIZATION_PROCESS: 600000, // 10 minutos
    CLEANUP_PROCESS: 300000, // 5 minutos
    GARBAGE_COLLECTION: 300000, // 5 minutos
    MAINTENANCE_PROCESS: 1800000, // 30 minutos
    COORDINATION_SYNC: 10000, // 10 segundos
    HEALTH_CHECK: 10000, // 10 segundos
    MONITORING_UPDATE: 5000, // 5 segundos
    AUDITING_PROCESS: 30000, // 30 segundos
    SECURITY_SCAN: 60000, // 1 minuto
    PERFORMANCE_ANALYSIS: 120000, // 2 minutos
    RESOURCE_ANALYSIS: 60000, // 1 minuto
    COMMUNICATION_ANALYSIS: 30000, // 30 segundos
    WORKFLOW_ANALYSIS: 60000, // 1 minuto
    TASK_ANALYSIS: 30000, // 30 segundos
    DATABASE_ANALYSIS: 120000, // 2 minutos
    API_ANALYSIS: 60000, // 1 minuto
    WEB_ANALYSIS: 60000, // 1 minuto
    MIGRATION_ANALYSIS: 300000, // 5 minutos
    BACKUP_ANALYSIS: 120000, // 2 minutos
    RESTORE_ANALYSIS: 300000, // 5 minutos
    MAINTENANCE_ANALYSIS: 180000, // 3 minutos
    SCALING_ANALYSIS: 120000, // 2 minutos
    FAILOVER_ANALYSIS: 60000, // 1 minuto
    RECOVERY_ANALYSIS: 120000, // 2 minutos
    OPTIMIZATION_ANALYSIS: 180000, // 3 minutos
    CLEANUP_ANALYSIS: 60000, // 1 minuto
    GARBAGE_COLLECTION_ANALYSIS: 60000, // 1 minuto
    SYSTEM_ANALYSIS: 300000 // 5 minutos
  },

  // Intervalos
  INTERVALS: {
    COORDINATION_SYNC: 30000, // 30 segundos
    HEALTH_CHECK: 60000, // 1 minuto
    MONITORING_UPDATE: 30000, // 30 segundos
    AUDITING_PROCESS: 300000, // 5 minutos
    SECURITY_SCAN: 600000, // 10 minutos
    PERFORMANCE_ANALYSIS: 300000, // 5 minutos
    RESOURCE_ANALYSIS: 120000, // 2 minutos
    COMMUNICATION_ANALYSIS: 60000, // 1 minuto
    WORKFLOW_ANALYSIS: 120000, // 2 minutos
    TASK_ANALYSIS: 60000, // 1 minuto
    DATABASE_ANALYSIS: 300000, // 5 minutos
    API_ANALYSIS: 120000, // 2 minutos
    WEB_ANALYSIS: 120000, // 2 minutos
    MIGRATION_ANALYSIS: 600000, // 10 minutos
    BACKUP_ANALYSIS: 300000, // 5 minutos
    RESTORE_ANALYSIS: 600000, // 10 minutos
    MAINTENANCE_ANALYSIS: 3600000, // 1 hora
    SCALING_ANALYSIS: 300000, // 5 minutos
    FAILOVER_ANALYSIS: 120000, // 2 minutos
    RECOVERY_ANALYSIS: 300000, // 5 minutos
    OPTIMIZATION_ANALYSIS: 600000, // 10 minutos
    CLEANUP_ANALYSIS: 300000, // 5 minutos
    GARBAGE_COLLECTION_ANALYSIS: 300000, // 5 minutos
    SYSTEM_ANALYSIS: 600000 // 10 minutos
  },

  // Códigos de error
  ERROR_CODES: {
    HIERARCHY_CREATION_FAILED: 'HIERARCHY_CREATION_FAILED',
    HIERARCHY_DELETION_FAILED: 'HIERARCHY_DELETION_FAILED',
    HIERARCHY_UPDATE_FAILED: 'HIERARCHY_UPDATE_FAILED',
    AGENT_REGISTRATION_FAILED: 'AGENT_REGISTRATION_FAILED',
    AGENT_DEREGISTRATION_FAILED: 'AGENT_DEREGISTRATION_FAILED',
    ROLE_ASSIGNMENT_FAILED: 'ROLE_ASSIGNMENT_FAILED',
    PERMISSION_GRANT_FAILED: 'PERMISSION_GRANT_FAILED',
    POLICY_APPLICATION_FAILED: 'POLICY_APPLICATION_FAILED',
    RULE_EVALUATION_FAILED: 'RULE_EVALUATION_FAILED',
    ESCALATION_PROCESS_FAILED: 'ESCALATION_PROCESS_FAILED',
    BACKUP_CREATION_FAILED: 'BACKUP_CREATION_FAILED',
    BACKUP_RESTORATION_FAILED: 'BACKUP_RESTORATION_FAILED',
    FAILOVER_PROCESS_FAILED: 'FAILOVER_PROCESS_FAILED',
    SCALING_PROCESS_FAILED: 'SCALING_PROCESS_FAILED',
    RECOVERY_PROCESS_FAILED: 'RECOVERY_PROCESS_FAILED',
    OPTIMIZATION_PROCESS_FAILED: 'OPTIMIZATION_PROCESS_FAILED',
    CLEANUP_PROCESS_FAILED: 'CLEANUP_PROCESS_FAILED',
    GARBAGE_COLLECTION_FAILED: 'GARBAGE_COLLECTION_FAILED',
    MAINTENANCE_PROCESS_FAILED: 'MAINTENANCE_PROCESS_FAILED',
    COORDINATION_SYNC_FAILED: 'COORDINATION_SYNC_FAILED',
    HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
    MONITORING_UPDATE_FAILED: 'MONITORING_UPDATE_FAILED',
    AUDITING_PROCESS_FAILED: 'AUDITING_PROCESS_FAILED',
    SECURITY_SCAN_FAILED: 'SECURITY_SCAN_FAILED',
    PERFORMANCE_ANALYSIS_FAILED: 'PERFORMANCE_ANALYSIS_FAILED',
    RESOURCE_ANALYSIS_FAILED: 'RESOURCE_ANALYSIS_FAILED',
    COMMUNICATION_ANALYSIS_FAILED: 'COMMUNICATION_ANALYSIS_FAILED',
    WORKFLOW_ANALYSIS_FAILED: 'WORKFLOW_ANALYSIS_FAILED',
    TASK_ANALYSIS_FAILED: 'TASK_ANALYSIS_FAILED',
    DATABASE_ANALYSIS_FAILED: 'DATABASE_ANALYSIS_FAILED',
    API_ANALYSIS_FAILED: 'API_ANALYSIS_FAILED',
    WEB_ANALYSIS_FAILED: 'WEB_ANALYSIS_FAILED',
    MIGRATION_ANALYSIS_FAILED: 'MIGRATION_ANALYSIS_FAILED',
    BACKUP_ANALYSIS_FAILED: 'BACKUP_ANALYSIS_FAILED',
    RESTORE_ANALYSIS_FAILED: 'RESTORE_ANALYSIS_FAILED',
    MAINTENANCE_ANALYSIS_FAILED: 'MAINTENANCE_ANALYSIS_FAILED',
    SCALING_ANALYSIS_FAILED: 'SCALING_ANALYSIS_FAILED',
    FAILOVER_ANALYSIS_FAILED: 'FAILOVER_ANALYSIS_FAILED',
    RECOVERY_ANALYSIS_FAILED: 'RECOVERY_ANALYSIS_FAILED',
    OPTIMIZATION_ANALYSIS_FAILED: 'OPTIMIZATION_ANALYSIS_FAILED',
    CLEANUP_ANALYSIS_FAILED: 'CLEANUP_ANALYSIS_FAILED',
    GARBAGE_COLLECTION_ANALYSIS_FAILED: 'GARBAGE_COLLECTION_ANALYSIS_FAILED',
    SYSTEM_ANALYSIS_FAILED: 'SYSTEM_ANALYSIS_FAILED',
    HIERARCHY_LIMIT_EXCEEDED: 'HIERARCHY_LIMIT_EXCEEDED',
    AGENT_LIMIT_EXCEEDED: 'AGENT_LIMIT_EXCEEDED',
    ROLE_LIMIT_EXCEEDED: 'ROLE_LIMIT_EXCEEDED',
    PERMISSION_LIMIT_EXCEEDED: 'PERMISSION_LIMIT_EXCEEDED',
    POLICY_LIMIT_EXCEEDED: 'POLICY_LIMIT_EXCEEDED',
    RULE_LIMIT_EXCEEDED: 'RULE_LIMIT_EXCEEDED',
    ESCALATION_LIMIT_EXCEEDED: 'ESCALATION_LIMIT_EXCEEDED',
    BACKUP_LIMIT_EXCEEDED: 'BACKUP_LIMIT_EXCEEDED',
    MONITOR_LIMIT_EXCEEDED: 'MONITOR_LIMIT_EXCEEDED',
    AUDITOR_LIMIT_EXCEEDED: 'AUDITOR_LIMIT_EXCEEDED',
    SECURITY_AGENT_LIMIT_EXCEEDED: 'SECURITY_AGENT_LIMIT_EXCEEDED',
    PERFORMANCE_AGENT_LIMIT_EXCEEDED: 'PERFORMANCE_AGENT_LIMIT_EXCEEDED',
    RESOURCE_AGENT_LIMIT_EXCEEDED: 'RESOURCE_AGENT_LIMIT_EXCEEDED',
    COMMUNICATION_AGENT_LIMIT_EXCEEDED: 'COMMUNICATION_AGENT_LIMIT_EXCEEDED',
    WORKFLOW_AGENT_LIMIT_EXCEEDED: 'WORKFLOW_AGENT_LIMIT_EXCEEDED',
    TASK_AGENT_LIMIT_EXCEEDED: 'TASK_AGENT_LIMIT_EXCEEDED',
    DATABASE_AGENT_LIMIT_EXCEEDED: 'DATABASE_AGENT_LIMIT_EXCEEDED',
    API_AGENT_LIMIT_EXCEEDED: 'API_AGENT_LIMIT_EXCEEDED',
    WEB_AGENT_LIMIT_EXCEEDED: 'WEB_AGENT_LIMIT_EXCEEDED',
    MIGRATION_AGENT_LIMIT_EXCEEDED: 'MIGRATION_AGENT_LIMIT_EXCEEDED',
    BACKUP_AGENT_LIMIT_EXCEEDED: 'BACKUP_AGENT_LIMIT_EXCEEDED',
    RESTORE_AGENT_LIMIT_EXCEEDED: 'RESTORE_AGENT_LIMIT_EXCEEDED',
    MAINTENANCE_AGENT_LIMIT_EXCEEDED: 'MAINTENANCE_AGENT_LIMIT_EXCEEDED',
    SCALING_AGENT_LIMIT_EXCEEDED: 'SCALING_AGENT_LIMIT_EXCEEDED',
    FAILOVER_AGENT_LIMIT_EXCEEDED: 'FAILOVER_AGENT_LIMIT_EXCEEDED',
    RECOVERY_AGENT_LIMIT_EXCEEDED: 'RECOVERY_AGENT_LIMIT_EXCEEDED',
    OPTIMIZATION_AGENT_LIMIT_EXCEEDED: 'OPTIMIZATION_AGENT_LIMIT_EXCEEDED',
    CLEANUP_AGENT_LIMIT_EXCEEDED: 'CLEANUP_AGENT_LIMIT_EXCEEDED',
    GARBAGE_COLLECTION_AGENT_LIMIT_EXCEEDED: 'GARBAGE_COLLECTION_AGENT_LIMIT_EXCEEDED',
    SYSTEM_AGENT_LIMIT_EXCEEDED: 'SYSTEM_AGENT_LIMIT_EXCEEDED',
    CUSTOM_AGENT_LIMIT_EXCEEDED: 'CUSTOM_AGENT_LIMIT_EXCEEDED',
    CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
    RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    INVALID_HIERARCHY: 'INVALID_HIERARCHY',
    INVALID_AGENT: 'INVALID_AGENT',
    INVALID_ROLE: 'INVALID_ROLE',
    INVALID_PERMISSION: 'INVALID_PERMISSION',
    INVALID_POLICY: 'INVALID_POLICY',
    INVALID_RULE: 'INVALID_RULE',
    INVALID_ESCALATION: 'INVALID_ESCALATION',
    INVALID_BACKUP: 'INVALID_BACKUP',
    INVALID_MONITOR: 'INVALID_MONITOR',
    INVALID_AUDITOR: 'INVALID_AUDITOR',
    INVALID_SECURITY_AGENT: 'INVALID_SECURITY_AGENT',
    INVALID_PERFORMANCE_AGENT: 'INVALID_PERFORMANCE_AGENT',
    INVALID_RESOURCE_AGENT: 'INVALID_RESOURCE_AGENT',
    INVALID_COMMUNICATION_AGENT: 'INVALID_COMMUNICATION_AGENT',
    INVALID_WORKFLOW_AGENT: 'INVALID_WORKFLOW_AGENT',
    INVALID_TASK_AGENT: 'INVALID_TASK_AGENT',
    INVALID_DATABASE_AGENT: 'INVALID_DATABASE_AGENT',
    INVALID_API_AGENT: 'INVALID_API_AGENT',
    INVALID_WEB_AGENT: 'INVALID_WEB_AGENT',
    INVALID_MIGRATION_AGENT: 'INVALID_MIGRATION_AGENT',
    INVALID_BACKUP_AGENT: 'INVALID_BACKUP_AGENT',
    INVALID_RESTORE_AGENT: 'INVALID_RESTORE_AGENT',
    INVALID_MAINTENANCE_AGENT: 'INVALID_MAINTENANCE_AGENT',
    INVALID_SCALING_AGENT: 'INVALID_SCALING_AGENT',
    INVALID_FAILOVER_AGENT: 'INVALID_FAILOVER_AGENT',
    INVALID_RECOVERY_AGENT: 'INVALID_RECOVERY_AGENT',
    INVALID_OPTIMIZATION_AGENT: 'INVALID_OPTIMIZATION_AGENT',
    INVALID_CLEANUP_AGENT: 'INVALID_CLEANUP_AGENT',
    INVALID_GARBAGE_COLLECTION_AGENT: 'INVALID_GARBAGE_COLLECTION_AGENT',
    INVALID_SYSTEM_AGENT: 'INVALID_SYSTEM_AGENT',
    INVALID_CUSTOM_AGENT: 'INVALID_CUSTOM_AGENT'
  },

  // Eventos del sistema
  EVENTS: {
    HIERARCHY_CREATED: 'hierarchy_created',
    HIERARCHY_DELETED: 'hierarchy_deleted',
    HIERARCHY_UPDATED: 'hierarchy_updated',
    AGENT_REGISTERED: 'agent_registered',
    AGENT_DEREGISTERED: 'agent_deregistered',
    ROLE_ASSIGNED: 'role_assigned',
    ROLE_REMOVED: 'role_removed',
    PERMISSION_GRANTED: 'permission_granted',
    PERMISSION_REVOKED: 'permission_revoked',
    POLICY_APPLIED: 'policy_applied',
    POLICY_REMOVED: 'policy_removed',
    RULE_EVALUATED: 'rule_evaluated',
    RULE_VIOLATED: 'rule_violated',
    ESCALATION_TRIGGERED: 'escalation_triggered',
    ESCALATION_RESOLVED: 'escalation_resolved',
    BACKUP_CREATED: 'backup_created',
    BACKUP_RESTORED: 'backup_restored',
    FAILOVER_TRIGGERED: 'failover_triggered',
    FAILOVER_COMPLETED: 'failover_completed',
    SCALING_TRIGGERED: 'scaling_triggered',
    SCALING_COMPLETED: 'scaling_completed',
    RECOVERY_TRIGGERED: 'recovery_triggered',
    RECOVERY_COMPLETED: 'recovery_completed',
    OPTIMIZATION_TRIGGERED: 'optimization_triggered',
    OPTIMIZATION_COMPLETED: 'optimization_completed',
    CLEANUP_TRIGGERED: 'cleanup_triggered',
    CLEANUP_COMPLETED: 'cleanup_completed',
    GARBAGE_COLLECTION_TRIGGERED: 'garbage_collection_triggered',
    GARBAGE_COLLECTION_COMPLETED: 'garbage_collection_completed',
    MAINTENANCE_TRIGGERED: 'maintenance_triggered',
    MAINTENANCE_COMPLETED: 'maintenance_completed',
    COORDINATION_SYNC_PERFORMED: 'coordination_sync_performed',
    HEALTH_CHECK_PERFORMED: 'health_check_performed',
    MONITORING_UPDATE_PERFORMED: 'monitoring_update_performed',
    AUDITING_PROCESS_PERFORMED: 'auditing_process_performed',
    SECURITY_SCAN_PERFORMED: 'security_scan_performed',
    PERFORMANCE_ANALYSIS_PERFORMED: 'performance_analysis_performed',
    RESOURCE_ANALYSIS_PERFORMED: 'resource_analysis_performed',
    COMMUNICATION_ANALYSIS_PERFORMED: 'communication_analysis_performed',
    WORKFLOW_ANALYSIS_PERFORMED: 'workflow_analysis_performed',
    TASK_ANALYSIS_PERFORMED: 'task_analysis_performed',
    DATABASE_ANALYSIS_PERFORMED: 'database_analysis_performed',
    API_ANALYSIS_PERFORMED: 'api_analysis_performed',
    WEB_ANALYSIS_PERFORMED: 'web_analysis_performed',
    MIGRATION_ANALYSIS_PERFORMED: 'migration_analysis_performed',
    BACKUP_ANALYSIS_PERFORMED: 'backup_analysis_performed',
    RESTORE_ANALYSIS_PERFORMED: 'restore_analysis_performed',
    MAINTENANCE_ANALYSIS_PERFORMED: 'maintenance_analysis_performed',
    SCALING_ANALYSIS_PERFORMED: 'scaling_analysis_performed',
    FAILOVER_ANALYSIS_PERFORMED: 'failover_analysis_performed',
    RECOVERY_ANALYSIS_PERFORMED: 'recovery_analysis_performed',
    OPTIMIZATION_ANALYSIS_PERFORMED: 'optimization_analysis_performed',
    CLEANUP_ANALYSIS_PERFORMED: 'cleanup_analysis_performed',
    GARBAGE_COLLECTION_ANALYSIS_PERFORMED: 'garbage_collection_analysis_performed',
    SYSTEM_ANALYSIS_PERFORMED: 'system_analysis_performed',
    HIERARCHY_LIMIT_EXCEEDED: 'hierarchy_limit_exceeded',
    AGENT_LIMIT_EXCEEDED: 'agent_limit_exceeded',
    ROLE_LIMIT_EXCEEDED: 'role_limit_exceeded',
    PERMISSION_LIMIT_EXCEEDED: 'permission_limit_exceeded',
    POLICY_LIMIT_EXCEEDED: 'policy_limit_exceeded',
    RULE_LIMIT_EXCEEDED: 'rule_limit_exceeded',
    ESCALATION_LIMIT_EXCEEDED: 'escalation_limit_exceeded',
    BACKUP_LIMIT_EXCEEDED: 'backup_limit_exceeded',
    MONITOR_LIMIT_EXCEEDED: 'monitor_limit_exceeded',
    AUDITOR_LIMIT_EXCEEDED: 'auditor_limit_exceeded',
    SECURITY_AGENT_LIMIT_EXCEEDED: 'security_agent_limit_exceeded',
    PERFORMANCE_AGENT_LIMIT_EXCEEDED: 'performance_agent_limit_exceeded',
    RESOURCE_AGENT_LIMIT_EXCEEDED: 'resource_agent_limit_exceeded',
    COMMUNICATION_AGENT_LIMIT_EXCEEDED: 'communication_agent_limit_exceeded',
    WORKFLOW_AGENT_LIMIT_EXCEEDED: 'workflow_agent_limit_exceeded',
    TASK_AGENT_LIMIT_EXCEEDED: 'task_agent_limit_exceeded',
    DATABASE_AGENT_LIMIT_EXCEEDED: 'database_agent_limit_exceeded',
    API_AGENT_LIMIT_EXCEEDED: 'api_agent_limit_exceeded',
    WEB_AGENT_LIMIT_EXCEEDED: 'web_agent_limit_exceeded',
    MIGRATION_AGENT_LIMIT_EXCEEDED: 'migration_agent_limit_exceeded',
    BACKUP_AGENT_LIMIT_EXCEEDED: 'backup_agent_limit_exceeded',
    RESTORE_AGENT_LIMIT_EXCEEDED: 'restore_agent_limit_exceeded',
    MAINTENANCE_AGENT_LIMIT_EXCEEDED: 'maintenance_agent_limit_exceeded',
    SCALING_AGENT_LIMIT_EXCEEDED: 'scaling_agent_limit_exceeded',
    FAILOVER_AGENT_LIMIT_EXCEEDED: 'failover_agent_limit_exceeded',
    RECOVERY_AGENT_LIMIT_EXCEEDED: 'recovery_agent_limit_exceeded',
    OPTIMIZATION_AGENT_LIMIT_EXCEEDED: 'optimization_agent_limit_exceeded',
    CLEANUP_AGENT_LIMIT_EXCEEDED: 'cleanup_agent_limit_exceeded',
    GARBAGE_COLLECTION_AGENT_LIMIT_EXCEEDED: 'garbage_collection_agent_limit_exceeded',
    SYSTEM_AGENT_LIMIT_EXCEEDED: 'system_agent_limit_exceeded',
    CUSTOM_AGENT_LIMIT_EXCEEDED: 'custom_agent_limit_exceeded',
    CONFIGURATION_ERROR: 'configuration_error',
    RESOURCE_EXHAUSTED: 'resource_exhausted',
    PERMISSION_DENIED: 'permission_denied',
    INVALID_HIERARCHY: 'invalid_hierarchy',
    INVALID_AGENT: 'invalid_agent',
    INVALID_ROLE: 'invalid_role',
    INVALID_PERMISSION: 'invalid_permission',
    INVALID_POLICY: 'invalid_policy',
    INVALID_RULE: 'invalid_rule',
    INVALID_ESCALATION: 'invalid_escalation',
    INVALID_BACKUP: 'invalid_backup',
    INVALID_MONITOR: 'invalid_monitor',
    INVALID_AUDITOR: 'invalid_auditor',
    INVALID_SECURITY_AGENT: 'invalid_security_agent',
    INVALID_PERFORMANCE_AGENT: 'invalid_performance_agent',
    INVALID_RESOURCE_AGENT: 'invalid_resource_agent',
    INVALID_COMMUNICATION_AGENT: 'invalid_communication_agent',
    INVALID_WORKFLOW_AGENT: 'invalid_workflow_agent',
    INVALID_TASK_AGENT: 'invalid_task_agent',
    INVALID_DATABASE_AGENT: 'invalid_database_agent',
    INVALID_API_AGENT: 'invalid_api_agent',
    INVALID_WEB_AGENT: 'invalid_web_agent',
    INVALID_MIGRATION_AGENT: 'invalid_migration_agent',
    INVALID_BACKUP_AGENT: 'invalid_backup_agent',
    INVALID_RESTORE_AGENT: 'invalid_restore_agent',
    INVALID_MAINTENANCE_AGENT: 'invalid_maintenance_agent',
    INVALID_SCALING_AGENT: 'invalid_scaling_agent',
    INVALID_FAILOVER_AGENT: 'invalid_failover_agent',
    INVALID_RECOVERY_AGENT: 'invalid_recovery_agent',
    INVALID_OPTIMIZATION_AGENT: 'invalid_optimization_agent',
    INVALID_CLEANUP_AGENT: 'invalid_cleanup_agent',
    INVALID_GARBAGE_COLLECTION_AGENT: 'invalid_garbage_collection_agent',
    INVALID_SYSTEM_AGENT: 'invalid_system_agent',
    INVALID_CUSTOM_AGENT: 'invalid_custom_agent'
  }
} as const;

// Exportar tipos derivados de las constantes
export type HierarchyLevel = typeof HIERARCHY_CONSTANTS.HIERARCHY_LEVELS[keyof typeof HIERARCHY_CONSTANTS.HIERARCHY_LEVELS];
export type HierarchyType = typeof HIERARCHY_CONSTANTS.HIERARCHY_TYPES[keyof typeof HIERARCHY_CONSTANTS.HIERARCHY_TYPES];
export type HierarchyStatus = typeof HIERARCHY_CONSTANTS.HIERARCHY_STATUS[keyof typeof HIERARCHY_CONSTANTS.HIERARCHY_STATUS];
export type HierarchyRole = typeof HIERARCHY_CONSTANTS.HIERARCHY_ROLES[keyof typeof HIERARCHY_CONSTANTS.HIERARCHY_ROLES];