// Constantes para el sistema completo
export const SYSTEM_CONSTANTS = {
  // Versión del sistema
  VERSION: {
    MAJOR: 2,
    MINOR: 0,
    PATCH: 0,
    BUILD: 1,
    FULL: '2.0.0'
  },

  // Entornos del sistema
  ENVIRONMENTS: {
    DEVELOPMENT: 'development',
    TESTING: 'testing',
    STAGING: 'staging',
    PRODUCTION: 'production'
  },

  // Estados del sistema
  SYSTEM_STATUS: {
    INITIALIZING: 'initializing',
    RUNNING: 'running',
    MAINTENANCE: 'maintenance',
    ERROR: 'error',
    SHUTDOWN: 'shutdown'
  },

  // Modos del sistema
  SYSTEM_MODES: {
    STANDALONE: 'standalone',
    CLUSTER: 'cluster',
    DISTRIBUTED: 'distributed',
    CLOUD: 'cloud',
    EDGE: 'edge',
    HYBRID: 'hybrid'
  },

  // Configuración por defecto
  DEFAULT_CONFIG: {
    ENVIRONMENT: 'development',
    SYSTEM_MODE: 'standalone',
    DEBUG_MODE: true,
    LOG_LEVEL: 'info',
    MAX_CONCURRENT_AGENTS: 100,
    MAX_CONCURRENT_TASKS: 50,
    MAX_CONCURRENT_WORKFLOWS: 20,
    HEARTBEAT_INTERVAL: 30000,
    HEALTH_CHECK_INTERVAL: 60000,
    CLEANUP_INTERVAL: 300000,
    BACKUP_INTERVAL: 3600000,
    OPTIMIZATION_INTERVAL: 1800000,
    SECURITY_SCAN_INTERVAL: 300000,
    PERFORMANCE_ANALYSIS_INTERVAL: 300000,
    RESOURCE_ANALYSIS_INTERVAL: 120000,
    COMMUNICATION_ANALYSIS_INTERVAL: 60000,
    WORKFLOW_ANALYSIS_INTERVAL: 120000,
    MONITORING_ANALYSIS_INTERVAL: 60000,
    TASK_ANALYSIS_INTERVAL: 60000,
    SYSTEM_ANALYSIS_INTERVAL: 300000,
    CUSTOM_ANALYSIS_INTERVAL: 300000
  },

  // Límites del sistema
  SYSTEM_LIMITS: {
    MAX_AGENTS: 1000,
    MAX_TASKS: 10000,
    MAX_WORKFLOWS: 1000,
    MAX_HIERARCHIES: 100,
    MAX_COMMUNICATION_CHANNELS: 1000,
    MAX_MONITORING_METRICS: 10000,
    MAX_SECURITY_POLICIES: 1000,
    MAX_BACKUPS: 100,
    MAX_LOGS: 1000000,
    MAX_CONFIGS: 10000,
    MAX_CACHES: 100,
    MAX_DATABASES: 10,
    MAX_FILES: 1000000,
    MAX_COMPRESSIONS: 1000000,
    MAX_ENCRYPTIONS: 1000000,
    MAX_VALIDATIONS: 1000000,
    MAX_SERIALIZATIONS: 1000000,
    MAX_ENCODINGS: 1000000
  },

  // Timeouts del sistema
  SYSTEM_TIMEOUTS: {
    INITIALIZATION: 60000,
    SHUTDOWN: 30000,
    HEALTH_CHECK: 10000,
    HEARTBEAT: 30000,
    CLEANUP: 300000,
    BACKUP: 300000,
    RESTORE: 600000,
    OPTIMIZATION: 600000,
    SECURITY_SCAN: 300000,
    PERFORMANCE_ANALYSIS: 300000,
    RESOURCE_ANALYSIS: 120000,
    COMMUNICATION_ANALYSIS: 60000,
    WORKFLOW_ANALYSIS: 120000,
    MONITORING_ANALYSIS: 60000,
    TASK_ANALYSIS: 60000,
    SYSTEM_ANALYSIS: 300000,
    CUSTOM_ANALYSIS: 300000
  },

  // Códigos de error del sistema
  SYSTEM_ERROR_CODES: {
    INITIALIZATION_FAILED: 'SYSTEM_INITIALIZATION_FAILED',
    SHUTDOWN_FAILED: 'SYSTEM_SHUTDOWN_FAILED',
    HEALTH_CHECK_FAILED: 'SYSTEM_HEALTH_CHECK_FAILED',
    HEARTBEAT_FAILED: 'SYSTEM_HEARTBEAT_FAILED',
    CLEANUP_FAILED: 'SYSTEM_CLEANUP_FAILED',
    BACKUP_FAILED: 'SYSTEM_BACKUP_FAILED',
    RESTORE_FAILED: 'SYSTEM_RESTORE_FAILED',
    OPTIMIZATION_FAILED: 'SYSTEM_OPTIMIZATION_FAILED',
    SECURITY_SCAN_FAILED: 'SYSTEM_SECURITY_SCAN_FAILED',
    PERFORMANCE_ANALYSIS_FAILED: 'SYSTEM_PERFORMANCE_ANALYSIS_FAILED',
    RESOURCE_ANALYSIS_FAILED: 'SYSTEM_RESOURCE_ANALYSIS_FAILED',
    COMMUNICATION_ANALYSIS_FAILED: 'SYSTEM_COMMUNICATION_ANALYSIS_FAILED',
    WORKFLOW_ANALYSIS_FAILED: 'SYSTEM_WORKFLOW_ANALYSIS_FAILED',
    MONITORING_ANALYSIS_FAILED: 'SYSTEM_MONITORING_ANALYSIS_FAILED',
    TASK_ANALYSIS_FAILED: 'SYSTEM_TASK_ANALYSIS_FAILED',
    SYSTEM_ANALYSIS_FAILED: 'SYSTEM_SYSTEM_ANALYSIS_FAILED',
    CUSTOM_ANALYSIS_FAILED: 'SYSTEM_CUSTOM_ANALYSIS_FAILED',
    CONFIGURATION_ERROR: 'SYSTEM_CONFIGURATION_ERROR',
    RESOURCE_EXHAUSTED: 'SYSTEM_RESOURCE_EXHAUSTED',
    PERMISSION_DENIED: 'SYSTEM_PERMISSION_DENIED'
  },

  // Eventos del sistema
  SYSTEM_EVENTS: {
    INITIALIZED: 'system_initialized',
    SHUTDOWN: 'system_shutdown',
    HEALTH_CHECK_PERFORMED: 'system_health_check_performed',
    HEARTBEAT_SENT: 'system_heartbeat_sent',
    CLEANUP_PERFORMED: 'system_cleanup_performed',
    BACKUP_CREATED: 'system_backup_created',
    RESTORE_PERFORMED: 'system_restore_performed',
    OPTIMIZATION_PERFORMED: 'system_optimization_performed',
    SECURITY_SCAN_PERFORMED: 'system_security_scan_performed',
    PERFORMANCE_ANALYSIS_PERFORMED: 'system_performance_analysis_performed',
    RESOURCE_ANALYSIS_PERFORMED: 'system_resource_analysis_performed',
    COMMUNICATION_ANALYSIS_PERFORMED: 'system_communication_analysis_performed',
    WORKFLOW_ANALYSIS_PERFORMED: 'system_workflow_analysis_performed',
    MONITORING_ANALYSIS_PERFORMED: 'system_monitoring_analysis_performed',
    TASK_ANALYSIS_PERFORMED: 'system_task_analysis_performed',
    SYSTEM_ANALYSIS_PERFORMED: 'system_system_analysis_performed',
    CUSTOM_ANALYSIS_PERFORMED: 'system_custom_analysis_performed',
    CONFIGURATION_ERROR: 'system_configuration_error',
    RESOURCE_EXHAUSTED: 'system_resource_exhausted',
    PERMISSION_DENIED: 'system_permission_denied'
  }
} as const;

// Exportar tipos derivados de las constantes
export type SystemEnvironment = typeof SYSTEM_CONSTANTS.ENVIRONMENTS[keyof typeof SYSTEM_CONSTANTS.ENVIRONMENTS];
export type SystemStatus = typeof SYSTEM_CONSTANTS.SYSTEM_STATUS[keyof typeof SYSTEM_CONSTANTS.SYSTEM_STATUS];
export type SystemMode = typeof SYSTEM_CONSTANTS.SYSTEM_MODES[keyof typeof SYSTEM_CONSTANTS.SYSTEM_MODES];