name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to server
        run: |
          echo "🚀 Deploying to production server..."
          # Aquí irían los comandos de deploy específicos
          # Por ejemplo: rsync, scp, o comandos de tu servidor
          echo "✅ Deploy completed successfully!"

      - name: Notify deployment
        run: |
          echo "📢 Deployment notification sent"
          # Aquí podrías enviar notificaciones a Slack, Discord, etc.
